/**
 * ID do Módulo deve ser em snake_case
 */
export enum ModuleEnum {
  ALBUM = "album",
  ANIMATION = "animation",
  BACKGROUND_SOUND = "background_sound",
  BASE_MODULE = "base_module",
  BIBLE = "bible",
  BIBLE_SEARCH = "bible_search",
  CLOCK = "clock",
  COLLECTIONS = "collections",
  COUNTER = "counter",
  CUSTOM_COLLECTIONS = "custom_collections",
  CUSTOM_VIDEOS = "custom_videos",
  DRAW = "draw",
  FAVORITES = "favorites",
  HISTORY = "history",
  HYMNAL = "hymnal",
  LITURGY = "liturgy",
  LYRIC = "lyric",
  MEDIA = "media",
  MEDIA_DECK = "media_deck",
  MESSAGE_BOARD = "message_board",
  MUSIC_SEARCH = "music_search",
  MUSICS = "musics",
  NAME_DRAW = "name_draw",
  ONLINE_VIDEOS = "online_videos",
  OVERLAY = "overlay",
  REMOTE_CONTROL = "remote_control",
  SLIDE_EDITOR = "slide_editor",
  STOPWATCH = "stopwatch",
  THEME = "theme",
  TIMER = "timer",
  TIMER_WORSHIP = "timer_worship",
}
