export enum ModuleEnum {
  BACKGROUND_SOUND = "background_sound",
  BIBLE_SEARCH = "bible_search",
  CLOCK = "clock",
  COUNTER = "counter",
  CUSTOM_VIDEOS = "custom_videos",
  DRAW = "draw",
  HYMNAL = "hymnal",
  LITURGY = "liturgy",
  MEDIA = "media",
  MEDIA_DECK = "media_deck",
  MESSAGE_BOARD = "message_board",
  MUSIC_SEARCH = "music_search",
  NAME_DRAW = "name_draw",
  ONLINE_VIDEOS = "online_videos",
  OVERLAY = "overlay",
  STOPWATCH = "stopwatch",
  TIMER = "timer",
  TIMER_WORSHIP = "timer_worship",
}
